/**
 * Generate capabilities.ts and roleGrants.ts from Python sources.
 * Run: npm run sync:capabilities
 *
 * Sources of truth:
 *   - apps/agent/src/runtime/capabilities.py  → Capability enum
 *   - apps/agent/src/runtime/role_grants.json → roleGrants table
 *
 * Outputs (auto-generated — do NOT edit by hand):
 *   - apps/frontend/src/runtime/capability/capabilities.ts
 *   - apps/frontend/src/runtime/capability/roleGrants.ts
 */

import { readFileSync, writeFileSync, renameSync } from "fs";
import { resolve } from "path";

const root = resolve(__dirname, "..");

// --- Parse Python Capability enum ---
const pyEnum = readFileSync(
  resolve(root, "apps/agent/src/runtime/capabilities.py"),
  "utf-8"
);

const classMatch = pyEnum.match(/class Capability[\s\S]*?(?=\nclass |\Z)/);
if (!classMatch) {
  console.error("[sync-capabilities] Could not find Capability class in capabilities.py");
  process.exit(1);
}

// Reconstruct comment sections + fields preserving Python comment groups
const capLines: string[] = [];
for (const line of classMatch[0].split("\n")) {
  const commentMatch = line.match(/^\s+#\s*(.*)/);
  if (commentMatch) { capLines.push(`  // ${commentMatch[1]}`); continue; }
  const fieldMatch = line.match(/^\s+(\w+)\s*=\s*"([\w.]+)"/);
  if (fieldMatch) {
    const pad = " ".repeat(Math.max(1, 20 - fieldMatch[1].length));
    capLines.push(`  ${fieldMatch[1]}:${pad}"${fieldMatch[2]}",`);
  }
}

const fieldCount = capLines.filter(l => !l.trimStart().startsWith("//")).length;

const capabilitiesTs = `// MUST stay in sync with apps/agent/src/runtime/capabilities.py
// AUTO-GENERATED by scripts/sync-capabilities.ts — DO NOT EDIT manually.
// Regenerate with: npm run sync:capabilities

export const Capability = {
${capLines.join("\n")}
} as const;

export type CapabilityId = typeof Capability[keyof typeof Capability];
`;

// --- Parse role_grants.json and generate roleGrants.ts ---
const pyGrants: Record<string, string[]> = JSON.parse(
  readFileSync(resolve(root, "apps/agent/src/runtime/role_grants.json"), "utf-8")
);

const roleLines = Object.entries(pyGrants).map(([role, caps]) => {
  const capStr = caps.map(c => `    "${c}"`).join(",\n");
  return `  ${role}: [\n${capStr},\n  ]`;
});

const roleGrantsTs = `// MUST stay in sync with apps/agent/src/runtime/role_grants.json
// AUTO-GENERATED by scripts/sync-capabilities.ts — DO NOT EDIT manually.
// Regenerate with: npm run sync:capabilities
import type { CapabilityId } from './capabilities'

export const roleGrants: Record<string, CapabilityId[]> = {
${roleLines.join(",\n")},
}

export function roleGrantsFor(role: string): CapabilityId[] {
  return roleGrants[role] ?? []
}
`;

// --- Write atomically (tmp → rename) ---
const capsOut = resolve(root, "apps/frontend/src/runtime/capability/capabilities.ts");
const grantsOut = resolve(root, "apps/frontend/src/runtime/capability/roleGrants.ts");

writeFileSync(capsOut + ".tmp", capabilitiesTs, "utf-8");
writeFileSync(grantsOut + ".tmp", roleGrantsTs, "utf-8");
renameSync(capsOut + ".tmp", capsOut);
renameSync(grantsOut + ".tmp", grantsOut);

console.log(
  `[sync-capabilities] OK — ${fieldCount} capabilities, ${Object.keys(pyGrants).length} roles written.`
);
